server:
  port: 8080
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
debug: true
mybatis:
      mapper-locations: classpath:mappers/*.xml
      type-aliases-package: com.example.demo.entity
spring:
  datasource:
    url : jdbc:mysql://localhost:3306/myvuedb?useUnicode=true&characterEncoding=utf8&useSSL=false
    username : root
    password : 123456
    driverClassName : com.mysql.jdbc.Driver
logging:
  config: classpath:logback.xml
storage:
     location: D:\javaee2\demo\FileUplaod
