server:
  port: 8080
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
  
spring:
  datasource:
    url : jdbc:mysql://localhost:3306/myvuedb?useUnicode=true&characterEncoding=UTF8&useSSL=true
    username: root
    password: root
    driverClassName : com.mysql.jdbc.Driver
logging:
  config: classpath:logback.xml
  
mybatis:
      mapper-locations: classpath:mappers/*.xml
      type-aliases-package: com.example.demo.entity
      
storage:
     location: D:\javaee2\demo\FileUplaod
